// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: prodvana/insights/insights.proto

package insights

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Insight with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Insight) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Insight with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in InsightMultiError, or nil if none found.
func (m *Insight) ValidateAll() error {
	return m.validate(true)
}

func (m *Insight) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Description

	// no validation rules for Class

	switch v := m.SubjectOneof.(type) {
	case *Insight_Service:
		if v == nil {
			err := InsightValidationError{
				field:  "SubjectOneof",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetService()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, InsightValidationError{
						field:  "Service",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, InsightValidationError{
						field:  "Service",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetService()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return InsightValidationError{
					field:  "Service",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Insight_Application:
		if v == nil {
			err := InsightValidationError{
				field:  "SubjectOneof",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetApplication()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, InsightValidationError{
						field:  "Application",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, InsightValidationError{
						field:  "Application",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetApplication()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return InsightValidationError{
					field:  "Application",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Insight_Organization:
		if v == nil {
			err := InsightValidationError{
				field:  "SubjectOneof",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetOrganization()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, InsightValidationError{
						field:  "Organization",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, InsightValidationError{
						field:  "Organization",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetOrganization()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return InsightValidationError{
					field:  "Organization",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return InsightMultiError(errors)
	}

	return nil
}

// InsightMultiError is an error wrapping multiple validation errors returned
// by Insight.ValidateAll() if the designated constraints aren't met.
type InsightMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InsightMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InsightMultiError) AllErrors() []error { return m }

// InsightValidationError is the validation error returned by Insight.Validate
// if the designated constraints aren't met.
type InsightValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InsightValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InsightValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InsightValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InsightValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InsightValidationError) ErrorName() string { return "InsightValidationError" }

// Error satisfies the builtin error interface
func (e InsightValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInsight.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InsightValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InsightValidationError{}

// Validate checks the field values on Insight_Subject with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *Insight_Subject) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Insight_Subject with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Insight_SubjectMultiError, or nil if none found.
func (m *Insight_Subject) ValidateAll() error {
	return m.validate(true)
}

func (m *Insight_Subject) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return Insight_SubjectMultiError(errors)
	}

	return nil
}

// Insight_SubjectMultiError is an error wrapping multiple validation errors
// returned by Insight_Subject.ValidateAll() if the designated constraints
// aren't met.
type Insight_SubjectMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Insight_SubjectMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Insight_SubjectMultiError) AllErrors() []error { return m }

// Insight_SubjectValidationError is the validation error returned by
// Insight_Subject.Validate if the designated constraints aren't met.
type Insight_SubjectValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Insight_SubjectValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Insight_SubjectValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Insight_SubjectValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Insight_SubjectValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Insight_SubjectValidationError) ErrorName() string { return "Insight_SubjectValidationError" }

// Error satisfies the builtin error interface
func (e Insight_SubjectValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInsight_Subject.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Insight_SubjectValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Insight_SubjectValidationError{}
