// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: prodvana/common_config/dangerous_action.proto

package common_config

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DangerousAction with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DangerousAction) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DangerousAction with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DangerousActionMultiError, or nil if none found.
func (m *DangerousAction) ValidateAll() error {
	return m.validate(true)
}

func (m *DangerousAction) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Explanation

	if len(errors) > 0 {
		return DangerousActionMultiError(errors)
	}

	return nil
}

// DangerousActionMultiError is an error wrapping multiple validation errors
// returned by DangerousAction.ValidateAll() if the designated constraints
// aren't met.
type DangerousActionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DangerousActionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DangerousActionMultiError) AllErrors() []error { return m }

// DangerousActionValidationError is the validation error returned by
// DangerousAction.Validate if the designated constraints aren't met.
type DangerousActionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DangerousActionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DangerousActionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DangerousActionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DangerousActionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DangerousActionValidationError) ErrorName() string { return "DangerousActionValidationError" }

// Error satisfies the builtin error interface
func (e DangerousActionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDangerousAction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DangerousActionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DangerousActionValidationError{}
